### PR TITLE
Add example for conda in README.md

### PR DESCRIPTION
**Pull request by juhasch**
Add example from nehalecky to README.md on how to create and use conda receipe

### CODE REVIEW

**Comment by JanSchulz** [comment]
BTW. should I build this Repo in my package builder? https://github.com/JanSchulz/package-builder -> conda packages end up here: https://anaconda.org/janschulz/ (win, linux, osx; 2.7, 3.4, 3.5)

**Comment by juhasch** [comment]
I think this would be a good idea!
We should probably move this repo to jupyter-contrib first, to avoid even more confusion.

**Comment by damianavila** [comment]
LGTM

**Comment by JanSchulz** [comment]
@juhasch @damianavila Adding it to the package builder is no problem but it would be nice if the package would also get a tag for a version (aka a release :-))

**Comment by damianavila** [comment]
>  the package would also get a tag for a version (aka a release :-))

Yep... I defer the decision about when to make a release to @juhasch because he knows better the status quo of the repo...

**Pull request closed without merging**
