### PR TITLE
Restructure into package

### PR DESCRIPTION
**Pull request by jcb91**
move everything except tests into src/<package_name>

### CODE REVIEW

**Comment by jcb91** [comment]
also fix a few paths which get changed

**Comment by juhasch** [comment]
Great! Will look into it

**Comment by jcb91** [comment]
This is a minor part, pretty much just the renames that move files into the right place, plus modifications to any applicable paths. The bulk of the work of making it `pip`-compatible I'll put into another PR. It should make it easier for the main PR to be to this branch though, so the renames don't pollute the diff...

**Comment by jfbercher** [comment]
As far as I see, this is nice.

**Comment by juhasch** [comment]
Looks good to me so far.

**Comment by jcb91** [comment]
Apologies for the rebase, a couple of alterations to naming of packages.
Anyway, in summary, this now amounts to:

* move everything bar `tests` into `src/jupyter_contrib_nbextensions`
* rename `extensions` -> `jupyter_contrib_nbextensions.nbconvert_support`, since they're now all nbconvert things
* fix install script to use moved directories
* fix paths to moved nbextensions files (I got rid of the directories `usability`, `styling` etc.)
* rename `tests/test-postprocessors.py`, since it actually tests preprocessors!
* move highlighter config scripts into `jupyter_contrib_nbextensions.config_scripts` package
* remove redundant scripts in `src/jupyter_contrib_nbextensions/nbextensions/highlighter`
* lint python scripts to fix flake8 complaints

**Pull request merged**
