### PR TITLE
Fixing paths to latex_envs files. Also removing 'http:' prefix from f…

### LINKED ISSUE #296: Errors when loading Latex environment extension
On enabling the "(some) LaTeX environments for Jupyter" extension from the UI and reloading the notebook, I could see 404 errors (and a few more) on the console...

The first problem is the paths in `latex_envs.js`

`/nbextensions/latex_envs/bibInNb4.js` should be `/nbextensions/usability/latex_envs/bibInNb4.js`

Similar changes to paths need to be made to other references to js files under latex_envs.

On fixing the paths, I ran into a problem with loading fonts. I am running my notebook with https, but the fonts refer to a http cdn in `latex_envs.css`.

Fixed this by removing the `http:` from the font paths. Also, one of the font cdn is insecure as it probably has a self signed certificate - had to force chrome to ignore insecure content to get rid of errors.

Not sure what we can do about the insecure cdn, but the missing `usability` in the paths are easy to fix.

### PR DESCRIPTION
**Pull request by motleytech**
…ont paths - this allows loading fronts from https sites.

This fixes #296

Sorry about the trailing white spaces removal... had my editor set to do that. I think we can benefit from that as trailing whitespace is useless in js files and a waste.

For easier comparison, here is the diff with the trailing whitespace ignored ( added ?w=1 to the diff url )

https://github.com/ipython-contrib/IPython-notebook-extensions/pull/297/files?w=1

### CODE REVIEW

**Comment by jfbercher** [comment]
Hi, 
Thanks for reporting  [#296](https://github.com/ipython-contrib/IPython-notebook-extensions/issues/296) and fixing. I originally designed the extension to install in nbextensions/latex_envs but uploaded it to nbextensions/usability/latex_envs and forgot to update the hardcoded paths... This imply the paths errors you encountered and corrected. Thanks for that, it will be useful for those who install from the UI. 
I provided a link for a direct install from my ariginal repo. This still works, but I will shortly update my repo so as to remain coherent with this one. Also I will have to do a small update of the paths in the docs (eg. manual enable should be `jupyter nbextension enable usability/latex_envs/latex_envs`). I had personally no problem with fonts but this might be configuration dependent. 
Feel free to make further issues/PR/comments (perhaps at https://github.com/jfbercher/latex_envs), this is certainly useful.

**Comment by juhasch** [comment]
@jfbercher : OK to merge ?

**Comment by jfbercher** [comment]
Yes.
The PR is useful. Thanks.

Jean-François
http://www.esiee.fr/~bercherj

**Comment by juhasch** [comment]
Thank you @motleytech.

**Comment by motleytech** [comment]
@jfbercher 
Thanks for the explanation.
About the font issue, it arises if the notebook is run under https, because the font links are http:// based.

**Pull request merged**
