### PR TITLE
Make hierarchical collapse compatible with 3.x .

### PR DESCRIPTION
**Pull request by bjanssen**
This makes the hierarchical collapse extension compatible with IPython notebook 3.x .
It also resolves some issues that were present in the pervious version of this extension.

### CODE REVIEW

**Comment by bjanssen** [comment]
Found an issue with conversion of cells to markdown cells.
Will reopen the PR as soon as the issue is fixed.

**Comment by juhasch** [comment]
Thanks for updating the extension. Will you convert it to use the new 3.x `require.js` scheme, i.e.
```Javascript
define([
  'base/js/namespace',
  'base/js/events'
  ], function(IPython, events) {
  /* my code */
  });
});
```
You could also load you css file relative, instead of providing an absolute path then.

**Comment by bjanssen** [comment]
@juhasch not sure if this is what you mean.
Where can I find the description of the 3.x coding guidelines?
I was not aware such things as a new `require.js` scheme…

**Comment by damianavila** [comment]
>Where can I find the description of the 3.x coding guidelines?

There is no coding guidelines from the Jupyter/IPython js code because things are changing too fast latety...

**Comment by juhasch** [comment]
This is how you can load a CSS file locally (the require entry is important):

```Javascript
define([
    'base/js/namespace',
    'jquery',
    'require',
    'base/js/events'
], function(IPython, $, require, events) {

    /**
     * Load my own CSS file
     *
     * @param name add CSS file
     *
     */
    var load_css = function (name) {
        var link = document.createElement("link");
        link.type = "text/css";
        link.rel = "stylesheet";
        link.href = require.toUrl(name, 'css');
        document.getElementsByTagName("head")[0].appendChild(link);
    };    

        load_css( './mycssfile.css');
});
```

**Comment by bjanssen** [comment]
Loading via `load_css` caused problems. 
The current version works properly and loads `./main.css`.

**Comment by juhasch** [comment]
OK thanks. We can move the extension from `testing` to `usability` if you add a description of the extensions it in the Wiki. I would like all extensions to have documentation.

**Pull request merged**
