### PR TITLE
themysto

### PR DESCRIPTION
**Pull request by jcb91**
So, this is a fairly extensive set of changes, but in summary:

- overhaul installation mechanism to be a fully pip-idiomatic package, along with to a new command-line utility called `themysto` which does the configuration.
- Make nbextensions available to jupyter notebook through a server extension, rather than writing a hardcoded path to a config file. This is helpful in cases where the pip installation is performed to a virtual environment.
- Add a 'retirer' script to remove config and files from the current repo installation mechanism
- Add tests for configuration page, along with installation & retire mechanisms
- Add continuous integration testing on Travis for Linux & OS X, and on Appveyor for Windows
- Add code-coverage (for python only so far, though I guess js may also be possible through something like [gotwarlost/istanbul-middleware](https://github.com/gotwarlost/istanbul-middleware))
- Updates to configuration page:
  - reinstate selector link hrefs to give correct cursor (6bbeb9a63f7c5c33da0d03fdcbad0100020af497)
  - fix bugs with url encoding (4470c2b5c9adfdb38079772e98dce2e6c5358b2d)
  - don't list duplicated nbextensions twice. Instead, warn in server logs, identifying the yaml files in question. (c21a1986645655d7a4d2b1194227b8636ac304b9)

This should address, among others, #617, #607, #606, #579, #577, #576, #529, #527, #505, #457
and hopefully prevent us from hitting problems like #596, #558, #222.

This PR will need some extra changes before merge, since it currently refers to my fork of the repo in readme files and suchlike. The easiest way to test it may be from pip directly (see [README.rst#installation](https://github.com/jcb91/IPython-notebook-extensions/tree/0.0.4#installation) for details).

Any & all feedback welcome 😄

### CODE REVIEW

**Comment by janschulz** [comment]
> Make nbextensions available to jupyter notebook through a server extension, rather than writing a hardcoded path to a config file. This is helpful in cases where the pip installation is performed to a virtual environment.

How does this compare to the nb extension by the anaconda guys?

For the rest: too big to review :-/

**Comment by jcb91** [comment]
@janschulz 

> How does this compare to the nb extension by the anaconda guys?

Not quite sure which one you mean?

> For the rest: too big to review :-/

True. I can try to split it up into smaller chunks for separate PRs, hopefully...

**Comment by janschulz** [comment]
@jcb91 I think I meant this Repo: https://github.com/Anaconda-Platform/nb_config_manager

**Comment by jcb91** [comment]
> @jcb91 I think I meant this Repo: https://github.com/Anaconda-Platform/nb_config_manager

@janschulz well, that one just copies info about which nbextensions are enabled from user-specific config dir to environment config dir. Where the files for those nbextensions are stored is a separate issue, and that's what I'mm attempting to fix by providing them as part of a pip package, then patching the server's `nbextensions_path` using a server extension.

**Comment by jcb91** [comment]
for a smaller illustration of the technique in question, see #631, which uses the same technique to move all of the javascript for the config serverextension into a python package

**Comment by janschulz** [comment]
Ok, I found this:

```
+extension configuration
 +-----------------------
 +
 +Once you have installed the python package, you can use its ``themysto``
 +command-line script to write config files which will configure notebook and
 +nbconvert to use the jupyter server extensions, nbextensions, templates and
 +processors:
 +
 +::
 +
 +    themysto install
 +
 +The install command takes some options which can be used to set where the
 +config files are written: use
 +
 +* ``--user`` to write config files in the user's jupyter directories (default location)
 +* ``--system`` to configure in the system-wide jupyter directories
 +* ``--sys-prefix`` to respect system environment variables, used for example to
 +  configure in the jupyter directories of a virtual environment
 +
 +After the package's configuration has been installed, and the jupyter server
 +has been (re)started, simply go to the ``/nbextensions`` page in the notebook,
 +as noted above, to activate/deactivate and configure your notebook extensions.
 ```

and I have a question: What's the releationship to `jupyter nbextension install`? Is that just a wrapper?

**Comment by jcb91** [comment]
> What's the releationship to jupyter nbextension install? Is that just a wrapper?

the flags (`--user`, `--system`, `--sys-prefix`) are equivalent, since they just relate to where to find config files. However, rather than a wrapper, essentially I just skipped `jupyter nbextension install` by directly editing the jupyter server's `nbextensions_path` using a jupyter server extension (`themysto.nbextenions_injector`).

So, the `themysto install` command is pretty much an analogue of `jupyter serverextension install` for both `themysto.nbextenions_injector` and `themysto.nbextenions_configurator`.

Does (any of) that make sense?

**Comment by janschulz** [comment]
I'm a fan of using what upstream provides instead of inventing our own way and maybe get incompatible on the next version.

IMO the goal should be that this repo basically just hosts extensions and all the infrastructure should be upstream (including the `/nbextension` page for administrating the individual extensions).

**Comment by jcb91** [comment]
> I'm a fan of using what upstream provides instead of inventing our own way and maybe get incompatible on the next version.

Unfortunately, the upstream provision becomes incompatible from one version to the next. 
We could use the inbuilt `jupyter nbextension install --py` (I did in fact do this, before coming up with my current solution). The main problem I found with that approach was the inconsistent API of `jupyter.nbextensions` across jupyter versions (4.0 vs 4.1 vs 4.2 don't provide the same functions/class methods, see #618 for an illustration of this). Additionally, attempting to uninstall things with `jupyter.nbextensions` leaves us open to breaking things that people have deliberately changed.

> IMO the goal should be that this repo basically just hosts extensions and all the infrastructure should be upstream (including the /nbextension page for administrating the individual extensions).

I guess we could (quite easily) split the config page into a separate repo, and make that a dependency of this one.

I had the impression that part of the point of this repo was to make installation of (numerous) extensions simpler for end users, which is pretty much the point of my install/retire apps, attempting to polyfilla the huge cracks in the upstream installation process. But, perhaps it'd be better to limit the scope of things provided by this repo, as you suggest. I'd be interested to know what everyone else thinks too... @juhasch, @jfbercher, any thoughts on the installation/configuration front?

**Comment by juhasch** [comment]
Sorry for being slow to answer. I agree that changes are required to the repo and the way extensions are installed.

What do most people seem to want ?
This is my interpretation of mailing list and github issues:

Usually they like to add some functionality the base notebook does not give them. So most important is 
- finding an extensions
- providing this functionality
- having at least some basic documentation
- easy installation, activation and deactivation
- extensions should not mess around too much with their configuration / should just work
- instructions do not conflict with the 'official' documentation

This could mean:
* installing a single extension should be possible without copying the full repo and the configuration page server extension  ('I just want this single extension...'). 
* They should also be installable using the 'official' method in some way
* The config server extension should be split into a separate repo

As the official notebook extension installation method is in some regards inferior to what we do, I believe we still need our own installation methods. So having a 'super-installer/configurator' like 'themysto' is quite useful. My suggestion would be to split this off as a separate repo, and adding it as a `jupyter` subcommand, i.e. calling it through the `jupyter <subcommand>` machinery.

**Comment by jcb91** [comment]
thanks @juhasch, some good ideas there. Some are easier than others to implement, but I think you're broadly right, and all are possible.

> * installing a single extension should be possible without copying the full repo and the configuration page server extension ('I just want this single extension...').

this is difficult to do straight from the repo, because github doesn't provide urls for single-directory archive downloads. One could install the pip package (which would include all extensions as data without installing them to jupyter), then install only the desired extension to jupyter, which has the desired effect, although it still requires the whole package to be downloaded. 

> * The config server extension should be split into a separate repo

easily done, and I think a good idea. I've already done the bulk of the work of making it into a self-contained pip package anyway. Also, as I mentioned before, we can always add/remove it as a dependency of this repo later on. I'll get that underway as `jupyter_nbextensions_configurator` unless anyone has another name they'd prefer?

> * They should also be installable using the 'official' method in some way

for most things, this is pretty simple using the `jupyter nbextension install --py` method (for those with notebook >= 4.2). Where it gets a bit more complicated is for those with earlier notebook versions, and for extensions which provide pre/post processors and templates which are for use with nbconvert (which doesn't provide similar extension installation machinery), and need to be added to configuration files etc. I think these will have to be covered by the super-installer/configurator wrapper mentioned below.

> My suggestion would be to split this off as a separate repo, and adding it as a `jupyter` subcommand, i.e. calling it through the `jupyter <subcommand>` machinery.

This is a fantastic idea! I hadn't thought of this before (indeed, it hadn't occurred to me that it was possible outside of the jupyter repos), but it would make a lot more sense to provide a command-line utility called via e.g. `jupyter contrib ...` rather than my existing `themysto ...`, which is a confusing name. I suggest putting all of the current config-modification into something like `jupyter contrib [un]configure all`, and then we can add sub-parts which can be [un]configured separately later. The config modification would then be a separate process from the pip-install. This seems pretty much what @janschulz meant by 

> My preference would be a package which brings all the extensions as data and installs them with a command

I think?

**Comment by juhasch** [comment]
>> installing a single extension should be possible without copying the full repo and the >>configuration page server extension ('I just want this single extension...').

>this is difficult to do straight from the repo, because github doesn't provide urls for single-directory >archive downloads. One could install the pip package (which would include all extensions as data >without installing them to jupyter), then install only the desired extension to jupyter, which has the >desired effect, although it still requires the whole package to be downloaded. 

I believe it would be OK requiring to download the complete repo. It simply should be possible to install a single extension using the official method, also. Nothing is more frustrating than looking for a single thing and being told you also need this and that...

**Comment by juhasch** [comment]
I like the idea of calling it `jupyter contrib` and then doing thinks like
`jupyter contrib install <extension-name> ...` for a single extension
`juypter contrib install --all` for all extensions
`jupyter contrib config...`
etc

This should also make it clear it is not an 'official' thing but it belongs to the Jupyter ecosystem.

**Comment by juhasch** [comment]
And not to forget, with your really nice work there is already a lot done to get there.
As for splitting, I suggest at least for the spin-off packages to put them into jupyter-contrib instead of ipython-contrib now.

**Comment by jcb91** [comment]
> I suggest at least for the spin-off packages to put them into jupyter-contrib instead of ipython-contrib now

good idea, though I can't do any of that as I'm not a member (or whatever the appropriate term is) there...

**Comment by jfbercher** [comment]
I understand the `themysto` rationale and think  it is a right way to go (and really a super work :-). 
I like very much the `jupyter contrib` idea.

Among other possibilities, it is possible to install single extensions via `jupyter nbextension install https://rawgit.com/.../extension.zip --user`. Of course this suppose we can afford storing a zip version of the extension (since github does not give us this functionality). Similarly one could also pip-install a package embedding pre/post processors or templates for extensions that use them. 

It is a very nice work @jcb91

**Comment by juhasch** [comment]
@Carreau : Could you add @jcb91 to jupyter-contrib, and give us both the right to create repos ?

**Comment by jcb91** [comment]
Ok, thanks for feedback all! I've thrown together a standalone repo for the configurator at [jcb91/jupyter_nbextensions_configurator](https://github.com/jcb91/jupyter_nbextensions_configurator) (also [on pypi](https://pypi.python.org/pypi/jupyter_nbextensions_configurator), and I've attempted a build at [conda-forge/staged-recipes](https://github.com/conda-forge/staged-recipes/pull/869), but the post-link step, which is supposed to enable the extension, isn't currently working...).

**Comment by janschulz** [comment]
@jcb91 This might be a nice project for https://github.com/jupyter-incubator?

**Comment by Carreau** [comment]
> @Carreau : Could you add @jcb91 to jupyter-contrib, and give us both the right to create repos ?

Sorry just saw that. Made him owner as well, sorry for the delay. 
It would be really nice to move many of the things here into Jupyter itself. Though with the current policy which look like "only jupyter lab matters" I don't know how well that would be accepted.

**Comment by jcb91** [comment]
@Carreau thanks, I got a notification about `ipython-contrib`, but nothing seems to have changed from `jupyter-contrib` so far.

> It would be really nice to move many of the things here into Jupyter itself.

well, if you've anything you'd like PRed, I can give it a go. But as you say, it may not be the appropriate moment for that...

**Comment by jcb91** [comment]
btw, PR for separating the configurator is #644

**Comment by jcb91** [comment]
@janschulz you mean the configurator, or the `jupyter contrib` idea? I've not looked at the incubator before, the process seems somewhat daunting!

**Comment by Carreau** [comment]
> @Carreau thanks, I got a notification about ipython-contrib, but nothing seems to have changed from jupyter-contrib so far.

D'oh... leaving the tab open and not clicking on "invite"...
Should be ok now.

**Comment by janschulz** [comment]
@jcb91 I mena the configurator page and the "format" (yaml file, ...)

**Comment by jcb91** [comment]
@Carreau thanks, all good now!

@janschulz right, I see what you mean. Yeah, probably worth at least floating the idea around to get some exposure.

**Pull request closed without merging**
