### PR TITLE
Unbreak the table beautifier

### PR DESCRIPTION
**Pull request by janschulz**
The beautifier worked, but it seems that the commands after the beautifier were not executed anymore, as the ToC didn't update afterwards anymore...

### CODE REVIEW

**Comment by JanSchulz** [comment]
The notebook problem is in https://github.com/jupyter/notebook/issues/1207

**Comment by janschulz** [comment]
Can someon please test and then merge? This is slightly embarrassing that this slipped in :-(

**Comment by jcb91** [comment]
Looks ok to me. Could we remove the `debugger;` calls, as they're a bit annoying if you're trying to debug a different extension while this one is enabled :stuck_out_tongue:

**Comment by janschulz** [comment]
@jcb91 removed...

**Pull request merged**
