### PR TITLE
Only toggle collapse when clicking on icon directly

### PR DESCRIPTION
**Pull request by juhasch**
Original click area:
heading_1
New click area:
heading_2

### CODE REVIEW

**Comment by jcb91** [comment]
Although I see what you're getting at here, and it is a good plan, it only makes sense if the option to make the icons into buttons _isn't_ selected (as the whole button should be clickable).

**Comment by juhasch** [comment]
Sure. If I understand your code right, the `on('click')` function is only added when the icon is not a button.

**Comment by jcb91** [comment]
No, I think it's slightly different: the `on('click')` function is registered for all toggle controls (buttons or otherwise), and the `collapsible_headings_make_toggle_controls_buttons` config value just controls whether the `btn` and `btn-default` css classes are added...

**Comment by jcb91** [comment]
Something like jcb91@81973f55cce078718eb26fd7cabb40d93e9fb434 ought to do it...

**Comment by juhasch** [comment]
Thanks. I'll take a look.

**Pull request closed without merging**
