### PR TITLE
Equation numbering extension

### PR DESCRIPTION
**Pull request by juhasch**
* Enables automatic equation numbering
* Resets equation numbers and rerenders math on pressing toolbar button

### CODE REVIEW

**Comment by certik** [comment]
Thanks for making this extension. I think this is an important step towards making this work automatically in the notebook by default.

**Comment by ketch** [comment]
Awesome!

**Comment by lucasb-eyer** [comment]
Thank you for this!

**Comment by maccesch** [comment]
Nice!

**Comment by neeravbm** [comment]
@juhasch Equation numbering plugin is converting "x \\\\ y" to "x \ y" within the equation when downloaded as HTML file. Similarly it is converting f_x to f\<em\>x. I am not familiar with Jupyter but know HTML/CSS/JS. Can you let me know where should I fix the issue in code? I can then submit the changes as a pull request.

**Comment by jfbercher** [comment]
I do not see how this could come from @juhasch equation-numbering. It may come from `latex_envs` if you use it (which also provides automatic equation numbering). In such a case, please try to isolate which plugin is involved. If it were `latex_envs`,  try to update to a recent version at [Pypi](https://pypi.python.org/pypi/jupyter_latex_envs) or to the most recent version on [github](https://github.com/jfbercher/jupyter_latex_envs). If the problem persists, please post an example notebook somewhere plus the commands you use to convert to html.

**Pull request merged**
