### PR TITLE
FileNotFoundError is not available in Python 2

### PR DESCRIPTION
**Pull request by juhasch**
As noted in #585

### CODE REVIEW

**Comment by jcb91** [comment]
Rather than remove it's handling completely, perhaps we could check its errno, as with the oserror, and as discussed in http://stackoverflow.com/questions/21367320/searching-for-equivalent-of-filenotfounderror-in-python-2 ?

**Comment by juhasch** [comment]
Hmm, I guess `FileNotFoundError` is a subclass of OSError and corresponds to `errno ENOENT`.
https://docs.python.org/3/library/exceptions.html#FileNotFoundError

Maybe add this:
```
if ex.errno not in (errno.ENOTDIR, errno.ENOTEMPTY, errno.ENOENT):
```
 ?

**Comment by jcb91** [comment]
Yep, sounds about right

**Comment by juhasch** [comment]
Done. Thanks for the hint.

**Pull request merged**
