### PR TITLE
Notebook server extension for activating/deactivating notebook extensions

### PR DESCRIPTION
**Pull request by juhasch**
This PR adds a notebook server extension that listens to `/nbextensions/` and displays a page listing all notebook extensions. Notebooks can be activated/deactivated on this page.

It consists of three parts:

### 1. YAML config files
Each notebook extension needs a YAML file to describe it. Here is an example:
```Python
# IPython Notebook Extension Description
Name: Runtools
Description: Runtools provide a number of afunctions for working with code cells
Link: https://github.com/ipython-contrib/IPython-notebook-extensions/wiki/Runtools
Icon: icon.png
Main: main.js
```
### 2. The server extension nbextensions.py
When requesting `/nbextensions/` all YAML files in the nbextension subdirecory are scanned and a list of extensions is sent to the page. The page template is called `nbextensions.html`

### 3. A Javascript handler
Handles the buttons on the pages and activates/deactivates notebook extensions

It's not very pretty right now but a start.

### CODE REVIEW

**Comment by dsblank** [comment]
Excellent! I have some similar code, but it wasn't nearly this nice. 

I do suggest that you swap the columns, and perhaps put a border around each row. At first, I couldn't tell that the left column was related to the right column. Now that I understand, it makes sense, but could be more intuitive.

If this doesn't get accepted by IPython 3, can it be rolled into an extension itself?

**Comment by takluyver** [comment]
Nice! I'd certainly like to integrate this feature into IPython, though I don't know if we'll try to get it in for 3.0 or not. I'll put it on the agenda for tomorrow's dev meeting.

**Comment by dsblank** [comment]
I can't imagine anyone not wanting to use this. If it doesn't become part of 3.0, it will probably become the most common adaptation/customization. 

I would like to add a "Search" on this page that would search a common repository for Jupyter nbextensions, and have an easy "Install" button. In fact, I'm going to stop working on the hack that I was making for my students, and adapt this....

**Comment by juhasch** [comment]
This still needs some polishing. At least the visuals should be improved and the YAML files need to be checked if they really describe a notebook extensions.

This can be installed like any extension. I have made an install script for the Anaconda package that installs and configures the extensions. It says X64 but will work on Unix, too.

**Comment by dsblank** [comment]
Thanks! For those of us that don't use conda, here is the installer source:

https://binstar.org/juhasch/nbextensions

@juhasch This makes me want to build a /settings/ and add CodeMirror config options and IPython options. And a /store/ to have access to an "Jupyter Extension Store"...

**Comment by Carreau** [comment]
> @juhasch This makes me want to build a /settings/ and add CodeMirror config options and IPython options. And a /store/ to have access to an "Jupyter Extension Store"...

Welcome to our world, did already work on Traitlets help to be easily json-able in the goal of making a web frontend to configure...

**Comment by takluyver** [comment]
From the dev meeting yesterday: we will definitely want to integrate something like this into IPython, but we'd rather not start adding significant new features to 3.0 now - we are trying to get it ready to release. So please move this forward as an extension for now, and we'll look into integrating it post 3.x.

**Comment by juhasch** [comment]
I merged the server extensions with a few updates and added a short description. 
Please let me know if you have any comments how to improve the extension.

**Pull request merged**
