### PR TITLE
update `publishing/print_preview_toolbar_button` to 4.x

### PR DESCRIPTION
**Pull request by jcb91**

### CODE REVIEW

**Comment by juhasch** [comment]
Not sure if anybody uses this at all ?

**Comment by jcb91** [comment]
Nor me!

**Comment by juhasch** [comment]
There is a menu for exactly this, so let's remove this extension.

**Comment by jcb91** [comment]
Fair enough, I'll edit.

**Comment by jcb91** [comment]
Although, this seems to have been written when the menu item already existed, so I guess someone just wanted a button. It might be better though, to have an extension which would just provide toolbar buttons for arbitrary actions.

**Pull request merged**
