### PR TITLE
Add support for curses-style printing

### PR DESCRIPTION
**Pull request by jbn**
Lots of console-based programs print backspaces or solitary carriage-returns to mock progress meters. The most popular example in Python package: the `tqdm` library. Currently, `limit_output` doesn't account for control characters. This patch adds such support. 

To be explicit, this patch trades (potentially) increased memory usage for faster processing-time. The backspaces and CRs still print and take up space. But, given the usage of curses-style printing, I don't think the risk of memory exhaustion (or, tab memory-exhaustion yielding a tab-freeze) is lower than risk imposed by rewriting the output. And, given that unadorned Jupyter supports this style printing, this patch makes output muting "less surprising."

### CODE REVIEW

**Comment by jcb91** [comment]
Sounds good to me. I'd agree that we're unlikely to run into memory-exhaustion problems, and even if we do, we could always make this new curses-style behaviour optional if _really_ necessary (although, if you run into the problem, I think it's probably likely you had a bigger problem that caused it in the first place!).

**Comment by jbn** [comment]
I literally just found a weird regression that I don't get / can't fix at this moment. Perhaps it's best to revert for a day until I can fix it. 

Sorry, @jcb91!

**Comment by jcb91** [comment]
ahaha ok!

**Comment by maximsch2** [comment]
Any progress on the regression hunting? What was it by the way? I've just hit the progress-printing with limiting issue in Jupyter and was going to file a separate issue here.

**Pull request merged**
