### PR TITLE
Pip install attempt

### PR DESCRIPTION
**Pull request by jfbercher**
This is an attempt to get a kind of pip installable version of the repo, *directly from the repo*, as suggested many times eg #393. It is no more necessary to clone the repo since pip will do the download of the last version of the master branch for the user. Also pip automatically launches the install. 

- Please note that this may not be a "good practice" since the repo is actually not a python package, and cannot be uninstalled via pip, but only manually for now. 

This builds on the new conda installation recipe #417 and simply adds a setup.py that checks for the dependencies and then calls both install.py and configure_nbextensions (@juhasch, please note that I had to rename configure-nbextensions into configure_nbextensions because python's import do not like dashes in filenames). 

**Usage**: if the PR is accepted, installation will be possible via
`pip install  https://github.com/ipython-contrib/IPython-notebook-extensions/archive/master.zip --user`
verbose mode can be enabled with -v switch eg `pip -v install ...` , and upgrade with a --upgrade. A system install can be done by omitting the --user switch.  
If it it works, we will need to update the documentation. 

**Testing**: For now, install can be tested from my personal repo
`pip install  https://github.com/jfbercher/IPython-notebook-extensions/archive/pip-install.zip --user`

After a first install, the distribution can be updated either 
- by adding --upgrade at the end of the command-line
- by first "uninstalling" via `pip uninstall Python-contrib-nbextensions` (this is not a true uninstall but simply an erase of the install reference in the pip manager)

This PR was tested on debian 9, with a vanilla Python/Jupyter install, and under windows 8.1 + anaconda 2.3 distrib. 
Hope it will work for others and will be useful!

### CODE REVIEW

**Comment by jfbercher** [comment]
@juhasch, please note that I had to rename configure-nbextensions into configure\_nbextensions. I also included a couple of modifications 

- open(x, a+) instead of open(x,r) [to create the file if it doesn't exist]
- corrected the path for saving json config files; I think that jupyter_config_dir() was missing
- added a "r" before the string in an os.path.join() to interpret the string as raw. Otherwise it causes a bug in Windows when reading nbextensions.html. Specifically "c:\users" was interpreted as c: "unicode escape" etc

Best

**Comment by juhasch** [comment]
Thanks.I noticed a few things when trying this out:
- My old `jupyter_notebook_config.json` configuration was overwritten (I had `"open_browser" : false` in it)  and not appended. Not sure why. We should probably make a backup copy, anyway.
- We should add the local path `.` to the template path in nbconvert. Makes having local templates easier and is also the default in the current `jupyter_nbconvert_config.py` template in the repo. I don't understand where this happens.
- The `Python_contrib_nbextensions.egg-info`  and `dist` directories should be added to `.gitignore`

Looks good otherwise to me.

**Comment by jfbercher** [comment]
As far as I am concerned, my json configs are not overwrited? I have corrected a small error that may still have caused this. Anyway, I have introduced a backup of these files as well as for the jupyter_*_config.py. I have also updated the paths to include '.' in templates path.

**Comment by jfbercher** [comment]
## Another pip-install attempt
 I have worked out an alternative pip-install for the IPython-contrib collection. The idea is to make a small package that takes care of dependencies, and installs a script that in turn, can be used to download and install the current master. Installation of the distribution to the current user directories, configuration files and paths is then done by
```
Jupyter_nb_contribs.py install
```
and probably via 
```
Jupyter_nb_contribs.exe install
```
under windows. 

**Caution: for now, the installation still overwrites existing files..** If you have made modifications, then backup or simply rename your existing nbextensions directory. 

This package can be seen at https://github.com/jfbercher/Jupyter_contrib_nbextensions_install_utility and can be tried using
```
pip install https://rawgit.com/jfbercher/Jupyter_contrib_nbextensions_install_utility/master/dist/Jupyter_contrib_nbextensions_install_utility-0.0.1.tar.gz
```
Tests, comments, suggestions, PR are most welcome!

**Comment by juhasch** [comment]
Looks good. Will merge if you can rebase to current master.

**Pull request closed without merging**
